---
title: Rbindというプロジェクトが立ち上がったみたいです
author: kazutan
date: '2017-04-26'
slug: whatis-rbindio
categories:
  - R
  - R Markdown
tags:
  - R
  - blogdown
  - R Markdown
---

2017/04/26の朝に，以下のようなツイートが届きました:

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr">blogdown界の<a href="https://t.co/cIRkAK63nC">https://t.co/cIRkAK63nC</a>的なものを目指してるらしい。おもしろそう。<a href="https://twitter.com/kazutan">@kazutan</a> さんの解説を待とう。 <a href="https://t.co/aiEtH20kRE">https://t.co/aiEtH20kRE</a></p>&mdash; Hiroaki Yutani (@yutannihilation) <a href="https://twitter.com/yutannihilation/status/856995260479676416">2017年4月25日</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

というわけで調べてみました。3行でまとめると以下のとおりです:

- Yuhuiが「blogdown使ってRユーザーでBindしようぜ」と[Rbindio](https://github.com/rbind)というOrganizationをGitHub上に準備
- 「リポジトリをここに設置すれば簡単にブログやWebサイトを公開できるようにするよ」
- 「ドメイン名がない? `*.rbind.io`で準備できるよ!」

## Rbindとは

世の中にはWordPress.comのように，気軽にWebサイトやblogを設置できるサービスが存在します。これらを利用すれば楽に自分のサイトやブログを設置することが可能となります。しかしこれらは特定の会社によって提供されているものです。

そこでYuhuiを含んだ有志[^1]によって「コミュニティによるこういったサービスを提供しようじゃないか」と準備されたのがこのRbindというプロジェクトのようです。

[^1]: Yuhuiが発起人の一人だとは思いますが，本人からのメッセージを受け取ってるわけではないので確証は…でもRbindIO内リポジトリのContributorをチェックする限りほぼ間違いないでしょう。

### 理念的なもの

詳しくは[こちらのページ](https://support.rbind.io/about/)を参照してください。冒頭を引用します:

> The goal of the Rbind project is to provide a service like WordPress.com or Medium, but driven by the community1 instead of a certain company. We hope users can help each other to build the websites they want. Currently most websites in this project are built using the blogdown package, but you are welcome to use other tools if you want.
>
> To make it easier to discover websites and get inspirations from other people’s websites, we created the Github organization “rbind” as a central place to host all websites. For example, if you are curious about how a particular website was built, you may study its source files, or even ask the author via Github issues.

要点は以下の通り:

- コミュニティベースでWordPress.comみたいなサービスを提供したい
- Webサイトづくりにおいて，お互いに助け合いながらやっていきたい
- 現状は`blogdown`で作ってるのが多いけど，別に他のでも構わないよ!
- お互いのサイトを見つけたりインスピレーションが得られるよう，GitHubで**rbind**という組織準備して，ここに集約してホスティングすることにしたよ
    - それぞれのサイトで興味がでたらソースコードみればいいし，分からなければGitHub issuesで聞けるよ

また，こちらのページも参考にしてください:

- https://support.rbind.io/2017/04/24/launching-rbind-support/

### 参加資格

まあわりとゆるい感じです。上述のページでの該当箇所を引用します:

> We do not really have hard restrictions on what kind of websites we expect to see in Rbind, but we will certainly be happy to host websites related to R and/or statistics.

Rや統計に関連してるようなものなら大歓迎だよ!ということです。言語的な縛りについては...どうなんだろう?割とアリな気もするけど，だれかissuesに投げないかな。

### 参加方法

シンプルです。該当箇所を引用します[^2]:

[^2]: この文には脚注およびリンクが含まれていましたがここでは省略します。詳しくは元ページを参照してください。

> If you do not have a website yet, please file a Github issue and we can help you create one in the Rbind organization using blogdown, otherwise you can transfer your existing Github repo to Rbind. In either case, if you do not own a domain name, we can offer a subdomain *.rbind.io to you for free, and just let us know in your Github issue.

要点は以下の通り:

- もしまだWebサイトを持ってないなら，issuesにその旨を送ってくれれば私たちが手伝うよ
- もうWebサイトを持ってるなら，そのGitHubリポジトリを移行(transfer)すればいいだけだよ
- ドメイン名がないのなら，`*.rbind.io`のサブドメインをフリーで提供するよ

## メリットとデメリット

ここからは私の主観的な判断ですので，ご了承ください。

### メリット

blogdownによるWebサイト/ブログの構築・設置において，コミュニティサポートが得やすくなる

: このブログもblogdownで作っていますが，まだそれほど情報があるとは言えません。でもここに参加すれば，**あのYuhuiを含むコミュニティの方々からサポート**してもらいやすくなります。これ以上心強いものはないかもしれません。

ホスティングを気にせずWebサイト/ブログを準備できる

: 地味に面倒なのがこのあたりで，下手に自分でホスティングサービス探すよりも有効です。また自分がすでに有している独自ドメインも割当可能なので，サイトURLを変更せずに引っ越せます。

多くの人に見てもらえる，かも

: これは完全に無根拠な予想なのですが，ある程度集まってきたら[本家トップ(現在は404)](https://rbind.io)が整備されて「新着記事一覧」とかジャンル別とかにまとめられたりするんじゃないかなと，WordPress.comのトップをみながら思ってます。そうなると公開した記事がより多くの人に読まれることになるでしょう。

### デメリット

すでにあるリポジトリを引っ越すのが(ちょっとだけ)面倒

: 「もう運用してるしなぁ...引っ越す手続きもめんどくさい」と多少感じるかも。すでにblogdownで運用しているならそう感じるでしょう。余談ですがblogdownはHugoで生成してますが，WordPressからHugoに移行するためのWordPressプラグインは存在します[^3]。

[^3]: 未検証なので深くは言及しませんが，私はそのうちこれを使って過去の記事を移行しようかと思ってます。ただ多分面倒なことになりそうなんだよなぁ...記事数多いし。

多分こんなところです。

## まとめ

おそらくblogdownでこれから作っていくという方には，いい感じのサービスになるのではないでしょうか。なによりコミュニティ運用でこのようなサービスが立ち上がるというのは素敵だと思います。気になる方は気軽にissueで聞いてみてはいかがでしょうか。

**Enjoy!**

## 補足と参考資料

この[RBind Support](https://support.rbind.io/)では，blogdownのテクニカルサポート情報が挙げられていくそうです。なので**blogdownユーザーは確実にチェックすることをおすすめします**。

参考資料:

- [Launching the Rbind support website &middot; Rbind Support](https://support.rbind.io/2017/04/24/launching-rbind-support/)
- [A Technical Introduction to Yihui&#39;s personal website &middot; Rbind Support](https://support.rbind.io/2017/04/25/yihui-website/)
- [About Rbind Support &middot; Rbind Support](https://support.rbind.io/about/)
- [RBindio - GitHub](https://github.com/rbind)